[package]
name = "rebellion-render"
version = "0.1.0"
edition = "2021"

[features]
default = []
interface-test-fixtures = []

[dependencies]
rebellion-core = { path = "../rebellion-core" }
macroquad = "0.4"
egui-macroquad = "0.17"
image = { version = "0.25", default-features = false, features = ["bmp", "png"] }
nucleo-matcher = "0.3"
quad-snd = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
